### ISSUE TITLE
All images blown up after installing plug in

### ISSUE THREAD

**Issue by Ampif** [josephfusco/disable-responsive-images#2]
Hello Joseph, 

I've just uploaded the plugin in on my site: www.livingwithfelipe.com because some images were blurry on Safari 8.0.8

I'm on Wordpress 4.6.1

After installing the plugin, the issue wasn't solved but I noticed that some images were blow up in all browsers and on Safari 8.0.8 reduced. 

For example on the home page, the last image at the bottom, the paw print, is blown up:

http://livingwithfelipe.com/

and all the images on the right on this page too: (the plane, the badge, the coffee cup, the monkey..)

http://livingwithfelipe.com/power-up/

However they seem fine on this page:

http://livingwithfelipe.com/get-in-touch/

I've deavtivated and deleted the plug in but the issue still persists. 

Thank you, I appreciate your help. 

Amparo

**Comment by josephfusco** [comment]
@Ampif Are you still having issues with this?

**Comment by Ampif** [comment]
Hello, not anymore. Thank you.

I had to work around it. I can't remember how.
